import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "@/components/header";
import AuthTokenLogger from "@/components/AuthTokenLogger";
import { AppProviders } from "@/components/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: undefined, // remove themes
        variables: {
          colorPrimary: "var(--primary)",
          colorPrimaryForeground: "var(--primary-foreground)",
          colorBackground: "var(--card)",
          colorText: "var(--card-foreground)",
        },
        elements: {
          card: "bg-[hsl(var(--card))] text-[hsl(var(--card-foreground))]",
          popoverBox: "bg-[hsl(var(--card))] shadow-sm border",
          userButtonPopoverCard:
            "bg-[hsl(var(--card))] text-[hsl(var(--card-foreground))]",
        },
      }}
    >
      <html lang="en" suppressHydrationWarning>
        <body className={`${inter.className}`}>
          <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem
            disableTransitionOnChange
          >
            {/* header */}
            <Header></Header>
            <AppProviders>
              <AuthTokenLogger />
              <main className="min-h-screen">{children}</main>
            </AppProviders>
            {/* footer */}
            <footer className="bg-muted/50 py-12">
              <div className="container mx-auto px-4 text-center text-gray-200">
                <p>Made with ❤️ by Adithi</p>
              </div>
            </footer>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
